spring:
  datasource:
    hikari:
      jdbc-url: "jdbc:postgresql://localhost:5432/employeedb"
      maximum-pool-size: 10
      driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: "jdbc:postgresql://localhost:5432/employeedb"
    driver-class-name: org.postgresql.Driver

